### ISSUE TITLE
Design a chat platform for the ones in the same event

### ISSUE THREAD

**Issue by eevci** [dominozor/myEvent#1]
http://www.programmingforliving.com/2013/08/jsr-356-java-api-for-websocket-client-api.html 
https://blog.idrsolutions.com/2013/12/websockets-an-introduction/
http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/HomeWebsocket/WebsocketHome.html
might be helpful

**Comment by Khrotan** [comment]
This must be challenging, keep it up dominozor!

**Comment by eevci** [comment]
websocket chat services has been implemented, rest of it is going to be finished while designing gui.
